# Generated by Django 3.2 on 2021-04-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
