# Generated by Django 3.2 on 2021-04-23 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210422_1223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
