# Generated by Django 3.2 on 2021-04-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_blogcomment_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='views',
        ),
    ]
